name: release

on:
  push: null

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: install node
      uses: actions/setup-node@v5
      with:
        node-version: 22.x
    - name: install node dependencies
      run: npm install
    - name: build
      run: npm run build
    - name: release
      run: npm run release
      env:
        GITHUB_TOKEN: ${{ github.token }}
